apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: jtim-dev-cds #default #jtim-test
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-wfm-tpcl-rabbitmq-0 #jtim-prometheus-server #wfm-tpcl-prometheus-server